stages:
    - install_tools 
    - deploy_environment
    - install_ddl
    - build_service
    - deploy_service 
    - test 

variables:
  OPENSHIFT_SERVER: https://172.17.188.117:8443
  # OPENSHIFT_DOMAIN: apps.example.com
  # Configure this variable in Secure Variables:
  OPENSHIFT_TOKEN: mTCTVHH2MW7L6DkJJEXVmHjQxeAadKD5wzn1TEh18wI

install_tools:
    stage: install_tools
    tags:
        - ci
    script:
        - mkdir tools
        - wget https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
        - tar xzf openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
        - mv openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/* ./tools  
        - wget http://mirror.olnevhost.net/pub/apache/maven/binaries/apache-maven-3.2.2-bin.tar.gz
        - tar xvf apache-maven-3.2.2-bin.tar.gz
        - ls -l 
    artifacts:
        paths:
            - tools/        

deploy_environment: 
    stage: deploy_environment
    before_script:
        - wget https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
        - tar xzf openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
        - mkdir tools         
        - mv openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/* ./tools  
        - ./tools/oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
        - ./tools/oc project "$CI_PROJECT_NAME-$CI_PROJECT_ID" 2> /dev/null || oc new-project "$CI_PROJECT_NAME-$CI_PROJECT_ID"    
    tags:
        - ci
    script:
        - "./tool/oc get services imarcats-db 2> /dev/null || oc new-app -e MYSQL_USER=imarcats -e MYSQL_PASSWORD=imarcats -e MYSQL_DATABASE=imarcats -e MYSQL_ROOT_PASSWORD=passwd mysql --name=imarcats-db"